### PR TITLE
LORE-107 Update Threat Dragon Model

### PR DESCRIPTION
**Pull request by josephthweatt**
#### What does this PR do?
Updates Threat dragon model with threats and given feedback from the previous threat modeling meeting.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
 @mdang8
 @brendan-hofmann
@figliold 

#### How should this be tested? (List steps with links to updated documentation)
View Threat dragon JSON file and get back with any feedback on it.

#### What are the relevant tickets?
Fixes #LORE-107

### Screenshots
[Screen Shot 2019-06-19 at 3 33 32 PM](url)

### CODE REVIEW

**Comment by figliold** [comment]
We should remove the database and associated arrows as we don't know if/when we will have that piece of the system.

**Comment by figliold** [comment]
The Transformation system doesn't have an external API; it is an internal API.  We should change that on the diagram.

**Comment by figliold** [comment]
I think we should replace items 7,8, 9 with Apache NIFI Transformation Dataflow.  Also, failures do not go back to the API.

**Comment by figliold** [comment]
The Transformation System doesn't have an external API; it has an internal API.  We should change that on the diagram.

**Comment by figliold** [comment]
The API doesn't use the callback URL.  We should remove that arrow back to the client.

**Comment by figliold** [comment]
We need to show that the dataflow in Apache NIFI calls the callback url.

**Comment by bakejeyner** [comment]
Leaving a block comment of recommended changes:

1. `Transform Request` should have `Tampering` and `Denial of Service`.
2. `MIME Type Query` should drop the `Spoofing` threat, because the consequence of Spoofing is Information Disclosure, which is already modeled.
3. `Query Results` should have `Denial of Service`, for instance if a response contains large data, and `Repudiation` that logs where the response is coming from.
4. `Request Queue` should drop the `Multiple Consumers` threat, brought up by Josh at the meeting.
5. `Database` and `Blob store` shouldn't have any threats on it since it is outside the trust boundary.
6. General: If all the entities are run in a docker container, all entities should have the `Elevation of Privilege` threat where a user can possible login to the container as root.
7. General: If there is a possibility of a container/service crashing, a `Denial of Service` can happen. So make sure each entity that can crash has the `Denial of Service` threat, which is usually mitigated by the docker orchestration logic (i.e. docker swarm, kubernetes) that re-boots crashed containers.

**Pull request merged**
